export const CATEGORIES = [
  { id: 'electronics', name: 'Electronics', icon: '⚡', count: 1240 },
  { id: 'fashion', name: 'Fashion', icon: '👗', count: 3450 },
  { id: 'home', name: 'Home & Living', icon: '🏠', count: 2100 },
  { id: 'art', name: 'Art & Crafts', icon: '🎨', count: 890 },
  { id: 'tech', name: 'Tech & Gadgets', icon: '🔧', count: 1560 },
  { id: 'beauty', name: 'Beauty', icon: '✨', count: 2340 },
];

export const FEATURED_PRODUCTS = [
  {
    id: 1,
    name: 'Quantum Wireless Earbuds',
    price: 79.99,
    originalPrice: 129.99,
    image: 'https://picsum.photos/seed/earbuds/400/400',
    rating: 4.8,
    reviews: 342,
    seller: 'TechVault',
    badge: 'Best Seller',
    category: 'electronics',
  },
  {
    id: 2,
    name: 'Neural Link Smart Watch',
    price: 249.99,
    originalPrice: null,
    image: 'https://picsum.photos/seed/watch/400/400',
    rating: 4.6,
    reviews: 128,
    seller: 'FutureWear',
    badge: 'New',
    category: 'tech',
  },
  {
    id: 3,
    name: 'Holographic LED Desk Lamp',
    price: 59.99,
    originalPrice: 89.99,
    image: 'https://picsum.photos/seed/lamp/400/400',
    rating: 4.9,
    reviews: 567,
    seller: 'LuminaCraft',
    badge: 'Top Rated',
    category: 'home',
  },
  {
    id: 4,
    name: 'Cyberpunk Messenger Bag',
    price: 124.99,
    originalPrice: null,
    image: 'https://picsum.photos/seed/bag/400/400',
    rating: 4.7,
    reviews: 89,
    seller: 'UrbanEdge',
    badge: null,
    category: 'fashion',
  },
  {
    id: 5,
    name: 'AI-Powered Art Canvas',
    price: 199.99,
    originalPrice: 279.99,
    image: 'https://picsum.photos/seed/canvas/400/400',
    rating: 4.5,
    reviews: 203,
    seller: 'ArtifactStudio',
    badge: 'Limited',
    category: 'art',
  },
  {
    id: 6,
    name: 'Bio-Luminescent Face Serum',
    price: 44.99,
    originalPrice: null,
    image: 'https://picsum.photos/seed/serum/400/400',
    rating: 4.8,
    reviews: 412,
    seller: 'GlowLab',
    badge: 'Trending',
    category: 'beauty',
  },
  {
    id: 7,
    name: 'Zero-Gravity Floating Speaker',
    price: 149.99,
    originalPrice: 199.99,
    image: 'https://picsum.photos/seed/speaker/400/400',
    rating: 4.4,
    reviews: 156,
    seller: 'SonicWave',
    badge: null,
    category: 'electronics',
  },
  {
    id: 8,
    name: 'Neon Flex Running Shoes',
    price: 189.99,
    originalPrice: null,
    image: 'https://picsum.photos/seed/shoes/400/400',
    rating: 4.7,
    reviews: 298,
    seller: 'VelocityGear',
    badge: 'Hot',
    category: 'fashion',
  },
];

export const TOP_SELLERS = [
  { id: 1, name: 'TechVault', avatar: 'https://picsum.photos/seed/tv/100/100', rating: 4.9, products: 156, sales: '12.4k' },
  { id: 2, name: 'LuminaCraft', avatar: 'https://picsum.photos/seed/lc/100/100', rating: 4.8, products: 89, sales: '8.7k' },
  { id: 3, name: 'UrbanEdge', avatar: 'https://picsum.photos/seed/ue/100/100', rating: 4.7, products: 234, sales: '15.2k' },
  { id: 4, name: 'GlowLab', avatar: 'https://picsum.photos/seed/gl/100/100', rating: 4.9, products: 67, sales: '6.3k' },
];

export const ALL_PRODUCTS = [
  ...FEATURED_PRODUCTS,
  {
    id: 9,
    name: 'Plasma Desktop Organizer',
    price: 34.99,
    originalPrice: null,
    image: 'https://picsum.photos/seed/organizer/400/400',
    rating: 4.3,
    reviews: 78,
    seller: 'LuminaCraft',
    badge: null,
    category: 'home',
  },
  {
    id: 10,
    name: 'Smart Ring Controller',
    price: 89.99,
    originalPrice: 119.99,
    image: 'https://picsum.photos/seed/ring/400/400',
    rating: 4.6,
    reviews: 134,
    seller: 'TechVault',
    badge: 'Sale',
    category: 'tech',
  },
  {
    id: 11,
    name: 'Handcrafted Resin Pendant',
    price: 29.99,
    originalPrice: null,
    image: 'https://picsum.photos/seed/pendant/400/400',
    rating: 4.8,
    reviews: 456,
    seller: 'ArtifactStudio',
    badge: null,
    category: 'art',
  },
  {
    id: 12,
    name: 'Magnetic Levitation Plant Pot',
    price: 69.99,
    originalPrice: 99.99,
    image: 'https://picsum.photos/seed/plantpot/400/400',
    rating: 4.5,
    reviews: 210,
    seller: 'LuminaCraft',
    badge: 'Cool',
    category: 'home',
  },
];
